### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by SchaffRita** [Ayagikei/LifeUp-Wiki#1]
I am trying to set up the wiki to create a local environment and I run into an issue I can't seem to figure out.

**Steps**
1. GitHub Desktop
  1. installed it
  2. logged in with a normal account
  3. cloned the repository
2. NodeJS
  1. installed it
3. docsify - installed it from [here](https://docsify.js.org/#/quickstart)
4. I go into docs > open a command window here
5. Run serve.bat
6. I can see that it is working as expected:
```
Serving C:\GitHub\LifeUp-Wiki\docs now.
Listening at http://localhost:3000
```
7. I go to http://localhost:3000

**Expected Results**: I can see the local site and if I change a file, the changes are reflected after refreshing the page.
**Actual Results**: I am redirected to https://wiki.lifeupapp.fun/en/#/
* * *
**More Information**
I looked into the index.html file and found that it's basically a script that redirects me if the docs are opened from a browser:
```
<script type="text/javascript">
    var type = navigator.appName;
    if (type == "Netscape") {
      var lang = navigator.language;//获取浏览器配置语言，支持非IE浏览器
    } else {
      var lang = navigator.userLanguage;//获取浏览器配置语言，支持IE5+ == navigator.systemLanguage
    };
    var lang = lang.substr(0, 2);//获取浏览器配置语言前两位
    if (lang == "zh") {
      location.href="http://wiki.lifeupapp.fun/zh-cn/#/";
    } else if (lang == "en") {
      location.href="http://wiki.lifeupapp.fun/en/#/";
    } else {//其他语言编码时打开以下链接
      location.href="http://wiki.lifeupapp.fun/en/#/";
    };
</script>
```
I am not sure that this is good for others who want to modify this. 😅 If you can give me the answer, I can also update the main readme here so that it would include all the instructions for others to set up the environment with no issues.

**Comment by Ayagikei** [comment]
Hello, you can jump to the corresponding local test URL in the following ways:
1. http://localhost:3000/zh-cn/#/
2. http://localhost:3000/en/index.html#/

Currently, JS is used to judge the browser language to jump to the "absolute path", which can indeed be optimized into an "absolute path".

And please feel free to update the readme.

**Comment by SchaffRita** [comment]
Hi, indeed this was the only thing that I haven't tried.

The following ones work (that explicitly include `index.html`):
http://localhost:3000/en/index.html#/
http://localhost:3000/zh-cn/index.html#/

These ones don't (that do not include `index.html`)
http://localhost:3000/en/#/
http://localhost:3000/zh-cn/#/

I will create a tutorial for the readme to set up everything.
